AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ReportingWithAIAgent Backend - Node.js Lambda function with Claude Agent SDK for chart generation

Parameters:
  AnthropicApiKey:
    Type: String
    Description: Anthropic API Key for Claude Agent SDK
    NoEcho: true
    Default: ''
  SupabaseProjectRef:
    Type: String
    Description: Supabase Project Reference
    Default: ''
  SupabaseAccessToken:
    Type: String
    Description: Supabase Access Token
    NoEcho: true
    Default: ''
  GeminiApiKey:
    Type: String
    Description: "Your Google Gemini API Key for title suggestions and insights"
    NoEcho: true

Resources:
  ReportingAgentFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      FunctionName: ReportingWithAIAgent-Backend-Nodejs
      CodeUri: artifacts/function.zip
      Handler: index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          SUPABASE_PROJECT_REF: !Ref SupabaseProjectRef
          SUPABASE_ACCESS_TOKEN: !Ref SupabaseAccessToken
          LOG_LEVEL: INFO
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/ReportingWithAIAgent-Backend-Nodejs:*'
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ReportingAgentWebSocketApi}/*'
      Tags:
        Project: ReportingWithAIAgent
        Environment: !Ref AWS::StackName
        ManagedBy: CloudFormation

  ReportingAgentWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    DeletionPolicy: Delete
    Properties:
      Name: ReportingWithAIAgent-WebSocket-API
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      Tags:
        Project: ReportingWithAIAgent
        Environment: !Ref AWS::StackName
        ManagedBy: CloudFormation

  # WebSocket Integration (single integration for all routes)
  WebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ReportingAgentWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReportingAgentFunction.Arn}/invocations'

  # WebSocket Routes
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ReportingAgentWebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub 'integrations/${WebSocketIntegration}'

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ReportingAgentWebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub 'integrations/${WebSocketIntegration}'

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ReportingAgentWebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Sub 'integrations/${WebSocketIntegration}'

  # Lambda Permissions for WebSocket API
  ConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ReportingAgentFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ReportingAgentWebSocketApi}/*/*'

  # WebSocket Deployment and Stage
  ReportingAgentWebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref ReportingAgentWebSocketApi

  WebSocketLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub '/aws/apigateway/${ReportingAgentWebSocketApi}'
      RetentionInDays: 7

  ReportingAgentWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ReportingAgentWebSocketApi
      StageName: prod
      DeploymentId: !Ref ReportingAgentWebSocketDeployment
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50
        LoggingLevel: INFO
      AccessLogSettings:
        DestinationArn: !GetAtt WebSocketLogGroup.Arn
        Format: '$context.requestId $context.routeKey $context.status'
      Tags:
        Project: ReportingWithAIAgent
        Environment: !Ref AWS::StackName
        ManagedBy: CloudFormation

  # Gemini API Proxy Resources
  # Using Lambda proxy instead of HTTP integration due to CORS limitation:
  # Access-Control-Allow-Origin header only accepts single origin, not comma-separated list
  GeminiProxyFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      FunctionName: ReportingAgent-Gemini-Proxy
      CodeUri: ../function-gemini/
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          GEMINI_API_KEY: !Ref GeminiApiKey
      Events:
        GeminiProxyApi:
          Type: Api
          Properties:
            Path: /
            Method: any
            RestApiId: !Ref GeminiProxyApi
      Tags:
        Project: ReportingWithAIAgent
        Environment: !Ref AWS::StackName
        ManagedBy: CloudFormation

  GeminiProxyApi:
    Type: AWS::Serverless::Api
    DeletionPolicy: Delete
    Properties:
      Name: ReportingAgent-Gemini-Proxy
      StageName: prod
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingRateLimit: 50
          ThrottlingBurstLimit: 100
      Tags:
        Project: ReportingWithAIAgent
        Environment: !Ref AWS::StackName
        ManagedBy: CloudFormation


Outputs:
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref ReportingAgentFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"
  
  WebSocketEndpoint:
    Description: WebSocket API Gateway endpoint URL
    Value: !Sub "wss://${ReportingAgentWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${AWS::StackName}-WebSocketEndpoint"
      
  GeminiProxyEndpoint:
    Description: "REST API Gateway endpoint URL for Gemini API proxy with dynamic CORS"
    Value: !Sub "https://${GeminiProxyApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${AWS::StackName}-GeminiProxyEndpoint"